#!/usr/bin/env bash
# Assembles firmware/secrets.yaml from the environment plus the public CA file.
#
# The same script runs locally and in CI, so the two cannot drift. Credentials
# come from the environment (GitHub Actions secrets in CI, a local shell or
# password manager on your machine); the CA certificate is public and lives in
# the repository next to this script.
#
#   API_ENCRYPTION_KEY   openssl rand -base64 32
#   OTA_PASSWORD         openssl rand -hex 16
#   WEB_PASSWORD         login for the lamp's own web page
#   WEB_USERNAME         optional, defaults to "nexus"
#   MQTT_BROKER          broker hostname, no scheme, no port
#   MQTT_USERNAME        the SUBSCRIBE-ONLY credential — this ends up in the
#   MQTT_PASSWORD        published image, so it must never be able to publish
set -euo pipefail

cd "$(dirname "$0")"

missing=()
for v in API_ENCRYPTION_KEY OTA_PASSWORD WEB_PASSWORD MQTT_BROKER MQTT_USERNAME MQTT_PASSWORD; do
  [[ -n ${!v:-} ]] || missing+=("$v")
done
if (( ${#missing[@]} )); then
  printf 'make-secrets.sh: missing %s\n' "${missing[*]}" >&2
  exit 1
fi

if [[ ! -f mqtt_ca.pem ]]; then
  echo "make-secrets.sh: mqtt_ca.pem not found" >&2
  exit 1
fi

{
  echo "# Generated by make-secrets.sh. Do not commit, do not hand-edit."
  echo
  echo "api_encryption_key: \"${API_ENCRYPTION_KEY}\""
  echo "ota_password: \"${OTA_PASSWORD}\""
  echo
  echo "web_username: \"${WEB_USERNAME:-nexus}\""
  echo "web_password: \"${WEB_PASSWORD}\""
  echo
  echo "mqtt_broker: \"${MQTT_BROKER}\""
  echo "mqtt_username: \"${MQTT_USERNAME}\""
  echo "mqtt_password: \"${MQTT_PASSWORD}\""
  echo
  echo "mqtt_ca_cert: |"
  sed 's/^/  /' mqtt_ca.pem
} > secrets.yaml

echo "→ firmware/secrets.yaml written (broker ${MQTT_BROKER}, user ${MQTT_USERNAME})"
